name: Download, Unpack and Push
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  download-unpack-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - run: mkdir -p .cache html json lua
      - name: 'Download and Unpack'
        run: |
          for file in "html" "json" "lua"; do
            wget -O .cache/$file.zip "https://scrapmechanic.com/api/$file.zip" && unzip -o ".cache/$file.zip"
          done
          mv sm.lua lua/
      - name: '`git status`'
        id: git-status
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
      - name: '`git config`'
        if: steps.git-status.outputs.modified == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - name: '`git push`'
        if: steps.git-status.outputs.modified == 'true'
        run:  |
          git add -A
          git commit -m '[automated commit] update files'
          git push
